Try debugging on MP4 preview, and add animated GIF preview

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -50,9 +50,10 @@ jobs:
           pwd
           ls -al
           cd test
-          ./animate.sh ./frames_out/frames.mp4
+          ./animate.sh ./frames_out/frames.mp4 || find / -iname "*libblas.so.*" -ls 2>/dev/null
 
       - name: Convert output frames from PPMs to PNGs
+        if: success() || failure() # Run this even if the step above fails.
         shell: bash
         run: |
           pwd
@@ -62,7 +63,17 @@ jobs:
           cd frames_out
           ../animate.sh png && cd png && tar czf ../frames.tgz *.png
 
-      - name: Store PNGs and MP4
+      - name: Convert output frames from PPMs to animated GIF
+        if: success() || failure() # Run this even if the step above fails.
+        shell: bash
+        run: |
+          pwd
+          ls -al
+          cd test
+          cd frames_out
+          ../animate.sh frames.gif
+
+      - name: Store frame output files
         if: success() || failure()
         uses: actions/upload-artifact@v4
         with:
@@ -70,7 +81,7 @@ jobs:
           path: |
             test/frames_out/frames.mp4
             test/frames_out/frames.tgz
-
+            test/frames_out/frames.gif
 
       - name: upload vcd
         if: success() || failure()
@@ -80,3 +91,27 @@ jobs:
           path: |
             test/tb.vcd
             test/results.xml
+
+  frames_preview:
+    #needs: gds
+    runs-on: ubuntu-24.04
+    permissions:
+      pages: write      # to deploy to Pages
+      id-token: write   # to verify the deployment originates from an appropriate source
+    steps:
+      - name: Download frames
+        uses: actions/download-artifact@v4
+        with:
+          name: frames-rtl
+          path: gh-pages
+      - name: Display preview in workflow summary
+        shell: bash
+        run: |
+          PAGE_URL=${{ steps.deployment.outputs.page_url }}
+          PAGE_URL=$(echo "$PAGE_URL" | sed -e 's/\/$//')
+          cat << EOF >> $GITHUB_STEP_SUMMARY
+          # Animated frames preview
+          ![Animated GIF of tested frames]($PAGE_URL/frames.gif)
+
+          ![Animated GIF of tested frames]($PAGE_URL/test/frames_out/frames.gif)
+          EOF
